### ISSUE TITLE
Plugin Error  As it doesnot contain package.json file

### ISSUE THREAD

**Issue by hami777** [H4ad/webapp-whatsapp-sticker#1]
If we create another project , then after running it throws this error 
else {

        console.log("Error: exec proxy not found for :: " + service + " :: " + action);
        
        if(typeof fail === "function" ) {
            fail("Missing Command Error");
        }
    }
in cordova.js file

**Comment by H4ad** [comment]
Please comment on the steps you have taken so that I can reproduce the error.

**Comment by hami777** [comment]
steps to reproduce 
1) Download the Project 
2)run npm install or ionic serve 
3)install plugin( cordova plugin add cordova-whatsapp-sticker-plugin) OR npm i cordova plugin add cordova-whatsapp-sticker-plugin 
<img width="590" alt="Screen Shot 2019-05-21 at 9 43 08 AM" src="https://user-images.githubusercontent.com/21078289/58068926-e9495780-7bac-11e9-8f07-5adf4e521438.png">

4) Error will occur

**Comment by H4ad** [comment]
I fix that error with [this commit](https://github.com/H4ad/webapp-whatsapp-sticker/commit/91506a2f6d06a8e5e38786ef1a867b524d36c3ea). Please, see the diff and apply the changes.

**Comment by hami777** [comment]
Yes now there is no such error . Thanks
