### ISSUE TITLE
Not working on iphone and android

### ISSUE THREAD

**Issue by hami777** [H4ad/webapp-whatsapp-sticker#2]
else {
            pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_ERROR messageAsString:@"Ocorreu algum problema, as figurinhas não foram enviadas."]; }

**Comment by H4ad** [comment]
This bug was possibly introduced by some wrong changes during development, upgrade the plugin to the new version, 0.0.5. If the bug persists, create a new issue and place the error produced.

**Comment by hami777** [comment]
Steps to Reproduce 
1) Downlaod the Project
2) run npm install
3) run ionic cordova build ios
4)run the app
![Simulator Screen Shot - iPhone Xʀ - 2019-05-21 at 10 10 38](https://user-images.githubusercontent.com/21078289/58069980-bbfea880-7bb0-11e9-9189-278b9f746714.png)

**Comment by H4ad** [comment]
You need to make sure this phone has WhatsApp, otherwise an error will occur. If you installed WhatsApp, which version of Ios do you use?

**Comment by hami777** [comment]
Its Resolved Thankyou
